version: '3.1'

services:

    mssqlldb:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: ISAT_MSSQL_2017
        restart: always
        environment:
            - SA_PASSWORD=5Gi3re61sXehuSGxMqHX
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes:
            - C:\Users\Public\Docker\Volumes\ISAT_MSSQL_2017:/var/opt/mssql/data
        networks:
            - ISAT-DOCKER-NETWORK
        
networks: 
    ISAT-DOCKER-NETWORK:
        driver: bridge